language: c

compiler:
  - gcc

sudo: required
dist: trusty

before_install:
  - # wget http://sourceforge.net/projects/devkitpro/files/Automated%20Installer/devkitARMupdate.pl
  - export DEVKITPRO=$TRAVIS_BUILD_DIR/buildtools/devkitPro
  - export DEVKITARM=$DEVKITPRO/devkitARM
  - # export DEVKITPRO=/home/travis/devkitPro
  - # export DEVKITARM=${DEVKITPRO}/devkitARM

install:
  - # sudo perl devkitARMupdate.pl
  - # sudo rm ${DEVKITPRO}/devkitARM/bin/ndstool
  - # sudo cp ${DEVKITPRO2}/devkitARM/bin/ndstool ${DEVKITPRO}/devkitARM/bin/
  - sudo chmod 777 ${DEVKITPRO}

script:
  - sudo make -j 1
