language: c

compiler:
  - gcc

sudo: required
dist: trusty

before_install:
  - export DEVKITPRO=/home/travis/build/Caboosium/hiyaCFW/buildtools/devkitPro
  - export DEVKITARM=${DEVKITPRO}/devkitARM

install:


script:
  - sudo wine /home/travis/build/Caboosium/hiyaCFW/buildtools/make/bin/make.exe -j 1
