language: c

sudo: required
dist: trusty

before_install:
  - wget http://sourceforge.net/projects/devkitpro/files/Automated%20Installer/devkitARMupdate.pl
  - export DEVKITPRO=/home/travis/devkitPro
  - export DEVKITARM=${DEVKITPRO}/devkitARM
  - sudo apt install gcc

install:
  - sudo perl devkitARMupdate.pl

script:
  - make -j 2 -f
