language: c

compiler:
  - gcc

sudo: required
dist: percise

before_install:
  - wget http://sourceforge.net/projects/devkitpro/files/Automated%20Installer/devkitARMupdate.pl
  - export DEVKITPRO2=$TRAVIS_BUILD_DIR/buildtools/devkitPro
  - export DEVKITARM2=$DEVKITPRO/devkitARM
  - export DEVKITPRO=/home/travis/devkitPro
  - export DEVKITARM=${DEVKITPRO}/devkitARM

install:
  - sudo perl devkitARMupdate.pl
  - sudo rm ${DEVKITPRO}/devkitARM/bin/ndstool
  - sudo cp ${DEVKITPRO2}/devkitARM/bin/ndstool ${DEVKITPRO}/devkitARM/bin/

script:
  - sudo make -j 1
