language: c

sudo: required
dist: percise

before_install:
  - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
  - sudo add-apt-repository -y ppa:win-cross-dev/win-cross
  - sudo apt-get update -qq -y
  - sudo apt-get install -qq -y doxygen graphviz gcc-arm-none-eabi gcc-mingw-w64-x86-64 binutils-mingw-w64-x86-64 libssl-dev mingw64-openssl --allow-unauthenticated --fix-missing
  - wget http://sourceforge.net/projects/devkitpro/files/Automated%20Installer/devkitARMupdate.pl
  - export DEVKITPRO=/home/travis/devkitPro
  - export DEVKITARM=${DEVKITPRO}/devkitARM
  - sudo apt install gcc

install:
  - sudo perl devkitARMupdate.pl

script:
  - make -j 2 -k

env:
 global:
  - FLAGS="-q --prefix=$PWD/out"
  - secure: "GwNIOVZvxiqQDTikyaLjyNcz5UvrVE5wjoBfu6/vbzmBR1KS+QbVnYkbTv8enW8kua8ilJ3F4604HCc2pqu8d7B/ONHvgvkVTIIvczegketS136ZS8NdVyb1Lp18reVAIkYudxopkKfocwY9dAA33VZZ4OKp5aovQ1owtSJxxXeFjl7leS7MUzrv2ltkF/kZscPHEgIlw/EFWJpcW5bNUXkPh4aDjG6uR9lJRq8EHaMnELJwWtyEv34dmQ8SC70O5XOfxEy80iBs17mvNXykHXPtLpv061myxMJ84/4fGD6P/G7MT7qIWBew0wdY7FWkzWsZO1i6zfygGZPGGQD5I9QRcUSi7YFlxx9Nkm7ecrZbrU2UXhHtBi0kpnrPYAor9JlATOVjAP5UcNXZ/JD2Geb8jtEP+WT+MQt4tbOfObXJKiYdsLez9/xOZx3ReONoLNbKa4h+4j7bDdvAbxmDwcQaz8BNEeIZtqUnXMdOqK0amCxanhULrCA9sQmC2eaptCjilYjoCHBWe55/j+k0K3WFpEHjlv48uPsDx8kT0gO/fFdm4rQ+XSKhtQvqbWGMmkzQ1BMmE1Qd6D+GZirWrisDrs1ZeLrcWxGUv4mNdmwVnrFNwB2wLsus/JTJArQOvtdWbVC9x45xjGX5eUJfAg+8x3M/ppvuE2fKJ3lv94c="
  - secure: "GVfqB9TOUv9N4ow+7dw3SoIjiJxlZ1EYQs5hD9oF7OvSY/YgSwB9UHizyJNsq/A3X7E2UsDURKJ4HaY3Pt04TsmSZIjvlQMAZ/gw/pGlkr1XcQfbK6Jt3qP389IYxtM6mhH/EkfI6aYWW2qFWkmqyws3YLX3z69TVO6pthFwSm55r+2PmH+r1XbHwgeNcIs9C/wYo1pngAGtkaJwy/g6418j21dKlSZUCGe4Jd7ZF7Qj8jLmALy1dTk5Gnl6Mgta6fMo6+caZzruTT+PwgpHKOQZ4s/6YhUeRoixCNirhzGlhyYPXXsBD+DniqtNK5Dy9KzTKdgy/khlP+E60D8P0JH3L1J/a8DahJuZQw/XWRne91AcTYBS84zzdRGXeLv8RUf4glLY3mAAinqGX5bhKq3Ctq1adAfG7XhRGCJDJ3hkRVRAp1qCropqUsjrcUlmGnr4JfBi/oNYKrR1gXT/OMMRYHXnq1OTVj/OXv0lJCUyR+RzDM+ehM08PXaRKLJrrU/v7HkfAJULxagv2nJ/U9UMDy0CUWZrgCIIbbJ6XOTyJUDoZaiTElFTuZkvVAlUXrrESOA21zTU8gE6KiQ0yhEQtDjljae9Vn2Zdfxn96EX6JsymEF3yWxSa21nobV5KGwfzTyHEX4/YVErpN/LSO60GKsxVLXYO4isRYlflms="
