language: c

compiler:
  - gcc

sudo: required
dist: percise

before_install:
  - export DEVKITPRO=$TRAVIS_BUILD_DIR/buildtools/devkitPro
  - export DEVKITARM=$DEVKITPRO/devkitARM

install:
  - sudo chmod -R 777 ${DEVKITPRO}


script:
  - sudo make -j 1
