language: c

compiler:
  - clang
  - gcc

sudo: required
dist: trusty

before_install:
  - sudo mkdir /home/travis/build/Caboosium/backup
  - sudo cp /home/travis/build/Caboosium/hiyaCFW /home/travis/build/Caboosium/backup -r
  - sudo mkdir /home/travis/build/Caboosium/hiyaCFW/restore
  - sudo cp /home/travis/build/Caboosium/backup/hiyaCFW /home/travis/build/Caboosium/hiyaCFW/restore -r
  - wget http://sourceforge.net/projects/devkitpro/files/Automated%20Installer/devkitARMupdate.pl
  - export DEVKITPRO=/home/travis/devkitPro
  - export DEVKITARM=${DEVKITPRO}/devkitARM
  - git clone https://github.com/smealum/ctrulib.git

install:
  - sudo perl devkitARMupdate.pl
  - wget http://sourceforge.net/projects/devkitpro/files/devkitARM/devkitARM_r46/devkitARM_r46-x86_64-linux.tar.bz2
  - tar -vxjf devkitARM_r46-x86_64-linux.tar.bz2
  - sudo rm /home/travis/devkitPro/devkitARM -r -f
  - sudo mv ./devkitARM /home/travis/devkitPro

script:
  - ls
  - cd /home/travis/build/Caboosium/hiyaCFW/restore/hiyaCFW
  - ls
  - sudo make -j 1

env:
 global:
  - FLAGS="-q --prefix=$PWD/out"
  - secure: "GwNIOVZvxiqQDTikyaLjyNcz5UvrVE5wjoBfu6/vbzmBR1KS+QbVnYkbTv8enW8kua8ilJ3F4604HCc2pqu8d7B/ONHvgvkVTIIvczegketS136ZS8NdVyb1Lp18reVAIkYudxopkKfocwY9dAA33VZZ4OKp5aovQ1owtSJxxXeFjl7leS7MUzrv2ltkF/kZscPHEgIlw/EFWJpcW5bNUXkPh4aDjG6uR9lJRq8EHaMnELJwWtyEv34dmQ8SC70O5XOfxEy80iBs17mvNXykHXPtLpv061myxMJ84/4fGD6P/G7MT7qIWBew0wdY7FWkzWsZO1i6zfygGZPGGQD5I9QRcUSi7YFlxx9Nkm7ecrZbrU2UXhHtBi0kpnrPYAor9JlATOVjAP5UcNXZ/JD2Geb8jtEP+WT+MQt4tbOfObXJKiYdsLez9/xOZx3ReONoLNbKa4h+4j7bDdvAbxmDwcQaz8BNEeIZtqUnXMdOqK0amCxanhULrCA9sQmC2eaptCjilYjoCHBWe55/j+k0K3WFpEHjlv48uPsDx8kT0gO/fFdm4rQ+XSKhtQvqbWGMmkzQ1BMmE1Qd6D+GZirWrisDrs1ZeLrcWxGUv4mNdmwVnrFNwB2wLsus/JTJArQOvtdWbVC9x45xjGX5eUJfAg+8x3M/ppvuE2fKJ3lv94c="
  - secure: "GVfqB9TOUv9N4ow+7dw3SoIjiJxlZ1EYQs5hD9oF7OvSY/YgSwB9UHizyJNsq/A3X7E2UsDURKJ4HaY3Pt04TsmSZIjvlQMAZ/gw/pGlkr1XcQfbK6Jt3qP389IYxtM6mhH/EkfI6aYWW2qFWkmqyws3YLX3z69TVO6pthFwSm55r+2PmH+r1XbHwgeNcIs9C/wYo1pngAGtkaJwy/g6418j21dKlSZUCGe4Jd7ZF7Qj8jLmALy1dTk5Gnl6Mgta6fMo6+caZzruTT+PwgpHKOQZ4s/6YhUeRoixCNirhzGlhyYPXXsBD+DniqtNK5Dy9KzTKdgy/khlP+E60D8P0JH3L1J/a8DahJuZQw/XWRne91AcTYBS84zzdRGXeLv8RUf4glLY3mAAinqGX5bhKq3Ctq1adAfG7XhRGCJDJ3hkRVRAp1qCropqUsjrcUlmGnr4JfBi/oNYKrR1gXT/OMMRYHXnq1OTVj/OXv0lJCUyR+RzDM+ehM08PXaRKLJrrU/v7HkfAJULxagv2nJ/U9UMDy0CUWZrgCIIbbJ6XOTyJUDoZaiTElFTuZkvVAlUXrrESOA21zTU8gE6KiQ0yhEQtDjljae9Vn2Zdfxn96EX6JsymEF3yWxSa21nobV5KGwfzTyHEX4/YVErpN/LSO60GKsxVLXYO4isRYlflms="
